### ISSUE TITLE
2.6.1 不支持修改

### ISSUE THREAD

**Issue by TheSaltwaterRoom** [ZJamss/PVZ_Cheating#12]

**Comment by ZJamss** [comment]
![image](https://github.com/user-attachments/assets/27dd7e09-257b-4a4e-b8c9-5f13b6465925)
实测可以修改 注意窗口名为<植物大战僵尸杂交版v2.6.1+10个空格>，以后的版本获取不到句柄可以通过spy++获取窗口名再试

**Comment by ZJamss** [comment]
参考 #13
