### ISSUE TITLE
无法通过窗口名匹配V2.1版本的游戏进程

### ISSUE THREAD

**Issue by ByteLogHZ** [ZJamss/PVZ_Cheating#6]

**Comment by ZJamss** [comment]
描述一下遇到的问题

**Comment by ByteLogHZ** [comment]
找不到2.1版本的游戏进程！！！

**Comment by ZJamss** [comment]
> 找不到2.1版本的游戏进程！！！

注意2.1版本的窗口名最后多一个空格，可以使用spy++确定进程窗口名
![image](https://github.com/ZJamss/PVZ_Cheating/assets/76551468/85c245eb-163c-48b2-bc88-91972f4f1857)

**Comment by ByteLogHZ** [comment]
解决了！感谢作者大大！！！！
